### ISSUE TITLE
Push the clipboard into kill-ring

### ISSUE THREAD

**Issue by tuhdo** [bburns/clipmon#2]
Thanks for the nice package. While inserting current buffer is nice, it would be nicer if we have an option to insert it into the kill ring and later use packages like [browse-kill-ring](https://github.com/browse-kill-ring/browse-kill-ring) or [helm-kill-ring](http://tuhdo.github.io/static/part3/helm-kill-ring.gif) to retrieve the content.

**Comment by bburns** [comment]
Hmm, good idea - I'll make a new option called clipmon-action, which will take a fn or list of fns to run on detecting a change. The default will be 'insert, while 'kill-new will put the string into the kill-ring.

**Comment by bburns** [comment]
Okay, I pushed the changes with version 20140131. If you want to add to the kill-ring also you can do (setq clipmon-action '(insert kill-new)). I wasn't sure about setting this as the default - I haven't used the kill-ring much yet, though the browse-kill-ring function looks pretty nice. But maybe people wouldn't expect it to add things to the kill-ring by default. Anyway, it'll be up once melpa builds it.

**Comment by tuhdo** [comment]
Great, thanks. It is useful when you browse code and save copied pieces of code at once without having to swtich back and forth between the browswer and Emacs. Or I can simply use Emacs as a clipboard manager. It's ok not to use this as the default, but you should document them at the homepage.

**Comment by bburns** [comment]
Interesting idea to use Emacs as a clipboard manager - I guess you'd also want it to save the kill ring every now and then in case your system dies. I looked around but didn't find any reference to such a thing - here Sacha Chua is talking about using external clipboard managers - 
http://sachachua.com/blog/2013/12/decision-review-clipboard-managers-get-one/

Do you know of anything that will autosave the kill ring and restore it? If not I could add that feature also.

**Comment by bburns** [comment]
It looks like it would be simplest to just use savehist to persist the kill ring - I'll add that to the commentary/readme.
