### ISSUE TITLE
Clipmon not working on OS X?

### ISSUE THREAD

**Issue by priyadarshan** [bburns/clipmon#7]
Hello,

On OS X, when I activate clipmon, I get:

```
clipmon--clipboard-contents: Symbol’s function definition is void: x-selection-owner-p
```

Could it be related to: https://github.com/bburns/clipmon/issues/4#issuecomment-176000939 ?

**Comment by bburns** [comment]
Are you on Emacs 25 by chance? I think they renamed the function to `gui-selection-owner-p` in 25 - if so I'll just need to handle that case.

**Comment by priyadarshan** [comment]
Yes, I am on Emacs 25.0.94.1. Thank you for looking into this.
