### ISSUE TITLE
clipmon auto start in init file with emacsclient

### ISSUE THREAD

**Issue by emanresusername** [bburns/clipmon#8]
not sure if this is related to [this](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=22214) or not, but if i put the 
```elisp
(add-to-list 'after-init-hook 'clipmon-mode-start)
```
line in my init file and start emacsclient (using [this plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/emacs/emacsclient.sh) but also happens if i call emacsclient directly) then it hangs :(
this is awesome functionality! i just want it on all the time from when the emacs daemon/server starts, don't realize it's an issue till i go to the kill ring and realize, "shit, it wasn't capturing those things i highlighted :("
using emacs 24.5 with the cocoa app (brew installed) on mac osx 10.9.5

**Comment by bburns** [comment]
Thanks for catching that - yeah if it's hanging it's probably some timing issue, which is pretty complex - the simplest workaround would be to expose a new emacs internal variable. I'll see if I can dig into that this week - I've got some time to work on it now.

**Comment by emanresusername** [comment]
in the meantime, [reddit](https://www.reddit.com/r/emacs/comments/43a3uq/how_do_you_get_window_system_init_code_to_run/czgsbct) and [use-package](https://github.com/jwiegley/use-package) unblocked me
this is working for me in my init file now
```elisp
(use-package clipmon
  :config
  (add-hook 'after-make-frame-functions
	    (lambda (frame)
	      (when (display-graphic-p frame)
		(clipmon-mode-start)
		(clipmon-persist))))
  ;; TODO: solve `this emacs binary lacks sound support` error
  (setq clipmon-autoinsert-sound nil) 
  (setq clipmon-transform-suffix "
"))
```

**Comment by emanresusername** [comment]
@bburns [my issue here is resolved with the latest push](http://who-is-awesome.com) #13
